<a href="https://colab.research.google.com/github/jhamilton1975/AutoAgent/blob/main/Business_Statistics_E_news.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
## CRITERIA

In [8]:
### PROBLEM DEFINITION, QUESTIONS TO BE ANSWERED
##.                                                        BACKGROUND INFORMATION TO THE PROJECT:
#.  The design team of the company has researched and created a new landing page that has a new outline & more relevant content shown compared to the old page.
#   In order to test the effectiveness of the new landing page in gathering new subscribers, the Data Science team conducted an experiment by randomly selecting 100 users and dividing them equally
#   into two groups. The existing landing page was served to the first group (control group) and the new landing page to the second group (treatment group).
#.  Data regarding the interaction of users in both groups with the two versions of the landing page was collected. Being a data scientist in E-news Express,
#.  you have been asked to explore the data and perform a statistical analysis (at a significance level of 5%) to determine the effectiveness of the new landing page in
#.  gathering new subscribers for the news portal by answering the following questions:

##                                                          QUESTIONS:
#. (1) Do the users spend more time on the new landing page than on the existing landing page?
#. (2) Is the conversion rate (the proportion of users who visit the landing page and get converted) for the new page greater than the conversion rate for the old page?
#  (3) Does the converted status depend on the preferred language?
#  (4) Is the time spent on the new page the same for the different language users?

##.                                                         THE KEY POINTS IN THE PRESENTATION SHOULD BE:
#.  Business Overview of the problem and solution approach
#.  Key findings and insights which can drive business decisions
#.  Business recommendations
#.  Focus on explaining the key takeaways in an easy-to-understand manner.
#.  The inclusion of the potential benefits of implementing the solution will give you the edge.

In [9]:
### DATA BACKGROUND AND CONTENTS

In [10]:
#INSTALL THE DEPENDENCIES
!pip install numpy==1.25.2 pandas==1.5.3 matplotlib==3.7.1 seaborn==0.13.1 scipy==1.11.4 -q --user

  Installing build dependencies ... done
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [2]:
#IMPORT THE LIBRARIES
# Libraries to help with reading and manipulating data
import numpy as np
import pandas as pd

# Libraries to help with data visualization
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Library to help with statistical analysis
import scipy.stats as stats

In [3]:
#LOADING THE DATA
data = pd.read_csv('abtest.csv')

In [ ]:
#EXPLORATORY DATA ANALYSIS - Univariate and bivariate analysis

In [4]:
#view the first 10 rows of the dataset
data.head(10)

,user_id,group,landing_page,time_spent_on_the_page,converted,language_preferred
0,546592,control,old,3.48,no,Spanish
1,546468,treatment,new,7.13,yes,English
2,546462,treatment,new,4.40,no,Spanish
3,546567,control,old,3.02,no,French
4,546459,treatment,new,4.75,yes,Spanish
5,546558,control,old,5.28,yes,English
6,546448,treatment,new,5.25,yes,French
7,546581,control,old,6.53,yes,Spanish
8,546461,treatment,new,10.71,yes,French
9,546548,control,old,2.08,no,English

In [5]:
#view the last 10 rows of the dataset
data.tail(10)

,user_id,group,landing_page,time_spent_on_the_page,converted,language_preferred
90,546477,treatment,new,5.40,no,French
91,546451,treatment,new,8.47,yes,English
92,546566,control,old,8.35,no,French
93,546474,treatment,new,4.94,no,French
94,546550,control,old,3.05,no,English
95,546446,treatment,new,5.15,no,Spanish
96,546544,control,old,6.52,yes,English
97,546472,treatment,new,7.07,yes,Spanish
98,546481,treatment,new,6.20,yes,Spanish
99,546483,treatment,new,5.86,yes,English

In [11]:
#check the shape of the dataset
data.shape

(100, 6)

In [12]:
#check the dat types of the columns for the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 100 non-null    int64
 1   group                   100 non-null    object
 2   landing_page            100 non-null    object
 3   time_spent_on_the_page  100 non-null    float64
 4   converted               100 non-null    object
 5   language_preferred      100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [13]:
#statistical summary for the numerical variables
data.describe(include='number')

             user_id  time_spent_on_the_page
count     100.000000              100.000000
mean   546517.000000                5.377800
std        52.295779                2.378166
min    546443.000000                0.190000
25%    546467.750000                3.880000
50%    546492.500000                5.415000
75%    546567.250000                7.022500
max    546592.000000               10.710000

In [14]:
#statistical summary for the categorical variables
data.describe(include='object')

          group landing_page converted language_preferred
count       100          100       100                100
unique        2            2         2                  3
top     control          old       yes            Spanish
freq         50           50        54                 34

In [15]:
#check missing values
data.isnull().sum()

user_id                   0
group                     0
landing_page              0
time_spent_on_the_page    0
converted                 0
language_preferred        0
dtype: int64

In [19]:
#check for duplicates
data.duplicated().sum()   #total number of duplicates
#data.duplicated(subset=['user_id', 'group', 'landing_page', 'time_spent_on_the_page', 'converted', 'language_preferred']).sum()    #for each column

np.int64(0)